# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
matrix:
  include:
    - os: linux
      dist: trusty
      compiler:
      - gcc
      - clang
      r: release
      r_check_revdep: true
    - os: linux
      dist: trusty
      compiler: clang
      r: devel
    - os: osx
      osx_image: xcode7.4
      r: release
    - os: osx
      osx_image: xcode7.4
      r: devel
    - os: osx
      osx_image:
      - xcode6.4
      - xcode8
      r: release

sudo: false
cache: packages

env:
  - OS=$(uname -s)
  - _R_CHECK_CRAN_INCOMING_=TRUE

r_binary_packages:
  - stringi
  - Rcpp
  - RcppArmadillo
  - dbscan
  - testthat
  - devtools
  - covr

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11


after_success:
  - Rscript -e 'covr::codecov(Sys.getenv("TRAVIS_BRANCH"))'
