# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    env: R_XTRA_CXXFLAGS = -DARMA_32BIT_WORD
  - os: linux
    dist: trusty
    r: release
    env: R_XTRA_CXXFLAGS = -DARMA_64BIT_WORD
  - os: osx
    r: release
  - r: devel
    os: linux
    dist: trusty
  - r: devel
    os: osx

cache: packages

env:
  global:
  - OS=$(uname -s)

cran: http://cran.rstudio.com

r_packages:
  - testthat

r_binary_packages:
  - stringi
  - testthat
  - devtools
  - covr
  - rmarkdown
  - ggplot2
  
r_check_revdep: true

sudo: required

before_install: |
  mkdir ~/.R
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      
after_success:
  - Rscript -e 'covr::codecov(Sys.getenv("TRAVIS_BRANCH"))'
