# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
  - osx
r:
  - release
  - devel
dist: trusty
osx_image:
  - xcode7.4
  - xcode7.2

cache: packages

env:
  - OS=$(uname -s) _R_CHECK_CRAN_INCOMING_=TRUE

r_binary_packages:
  - stringi
  - Rcpp
  - RcppArmadillo
  - dbscan
  - testthat
  - devtools
  - covr

before_install: |
  mkdir ~/.R
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

after_success:
  - Rscript -e 'covr::codecov(Sys.getenv("TRAVIS_BRANCH"))'
