# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
  include:
  - os: linux
    dist: trusty
    r: release
  - os: osx
    osx_image: xcode7.4
    r: release
  - r: devel
    os: linux
    dist: trusty
    env: CXXFLAGS=-fPIC
  - r: devel
    os: linux
    dist: trusty
    env: CXXFLAGS=-fPIC

cache: packages

env:
  global:
  - OS=$(uname -s) _R_CHECK_CRAN_INCOMING_=TRUE

r_packages:
  - testthat

before_install: |
  mkdir ~/.R
  if [[ $TRAVIS_R_VERSION == '3.3.1' ]]; then Rscript -e 'install.packages("covr")'; fi
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - r-cran-devtools
      - r-cran-stringi
      
after_success:
  - if [[ $TRAVIS_R_VERSION == '3.3.1' ]]; then Rscript -e 'covr::codecov(Sys.getenv("TRAVIS_BRANCH"))'; fi
