# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
  - osx
r:
  - release
  - devel
dist: trusty

cache: packages

env:
  global:
  - OS=$(uname -s) _R_CHECK_CRAN_INCOMING_=TRUE

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - dbscan
  - testthat
  - covr

before_install: |
  mkdir ~/.R
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - r-cran-devtools
      
after_success:
  - Rscript -e 'covr::codecov(Sys.getenv("TRAVIS_BRANCH"))'
